[package]
name = "zookeeper-cache-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
petgraph = "0.6.5"
pin-project = "1.1.5"
tokio = { version = "1.38.0", features = ["full"] }
zookeeper-client = "0.8.0"
